# Use Node 8 as base image
FROM node:8.7.0

RUN mkdir -p /data/node_modules
RUN mkdir -p /data/app

# Install node dependencies
RUN npm install yarn

WORKDIR /data
COPY package.json yarn.lock /data/

RUN yarn --pure-lockfile

ENV PATH /data/node_modules/.bin:$PATH

ADD . /data/app
WORKDIR /data/app

RUN mkdir -p /data/app/logs
RUN chown -R node:node /data/app/logs
RUN chmod 777 /data/app/logs

# Default command
CMD ["yarn", "test"]
